version: '2'
services:

  web:
      image: nginx
      ports:
          - "80:80"
          - "443:443"
      links:
          - php
          - mysql
      volumes:
          - ./conf/nginx/default:/etc/nginx/conf.d
          - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      volumes_from:
          - code

  php:
      build: ./conf/php
      working_dir: /var/www/gemy
      volumes_from:
          - code

  mysql:
      image: mysql
      ports:
          - "3306:3306"
      environment:
          - "MYSQL_ROOT_PASSWORD=rootpassword"
          - "MYSQL_USER=gemyuser"
          - "MYSQL_PASSWORD=gemypass"
          - "MYSQL_DATABASE=gemytest"

  code:
      image: busybox
      volumes:
          - .:/var/www/gemy

